export const TIMEZONES = [
  { value: "Etc/GMT+12", label: "UTC-12:00" },
  { value: "Etc/GMT+11", label: "UTC-11:00 (Samoa)" },
  { value: "Pacific/Honolulu", label: "UTC-10:00 (Hawaii)" },
  { value: "America/Anchorage", label: "UTC-09:00 (Alaska)" },
  { value: "America/Los_Angeles", label: "UTC-08:00 (Pacific Time)" },
  { value: "America/Denver", label: "UTC-07:00 (Mountain Time)" },
  { value: "America/Chicago", label: "UTC-06:00 (Central Time)" },
  { value: "America/New_York", label: "UTC-05:00 (Eastern Time)" },
  { value: "America/Halifax", label: "UTC-04:00 (Atlantic Time)" },
  { value: "America/Argentina/Buenos_Aires", label: "UTC-03:00 (Argentina)" },
  { value: "Etc/GMT+2", label: "UTC-02:00 (South Sandwich Islands)" },
  { value: "Etc/GMT+1", label: "UTC-01:00 (Azores)" },
  { value: "UTC", label: "UTC+00:00 (Universal Time)" },
  { value: "Europe/London", label: "UTC+00:00 (London)" },
  { value: "Europe/Paris", label: "UTC+01:00 (Central European Time)" },
  { value: "Africa/Cairo", label: "UTC+02:00 (Cairo)" },
  { value: "Europe/Istanbul", label: "UTC+03:00 (Istanbul)" },
  { value: "Asia/Dubai", label: "UTC+04:00 (Dubai)" },
  { value: "Asia/Karachi", label: "UTC+05:00 (Pakistan)" },
  { value: "Asia/Dhaka", label: "UTC+06:00 (Bangladesh)" },
  { value: "Asia/Bangkok", label: "UTC+07:00 (Bangkok)" },
  { value: "Asia/Shanghai", label: "UTC+08:00 (China)" },
  { value: "Asia/Tokyo", label: "UTC+09:00 (Japan)" },
  { value: "Australia/Sydney", label: "UTC+10:00 (Sydney)" },
  { value: "Pacific/Noumea", label: "UTC+11:00 (New Caledonia)" },
  { value: "Pacific/Auckland", label: "UTC+12:00 (New Zealand)" },
  { value: "Pacific/Tongatapu", label: "UTC+13:00 (Tonga)" },
  { value: "Pacific/Kiritimati", label: "UTC+14:00 (Kiritimati)" },
]
